// app/pages/auth/register.vue
<script setup lang="ts">
definePageMeta({
    layout: "empty",
});

import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { toast } from "vue-sonner";

const formSchema = toTypedSchema(
    z.object({
        username: z.string(),
        email: z.email("Invalid email address"),
        password: z.string(),
    }),
);

const form = useForm({
    validationSchema: formSchema,
});

const auth = useAuthClient();
const onSubmit = form.handleSubmit(async (values) => {
    const usr = await auth.signUp.email({
        name: values.username,
        email: values.email,
        password: values.password,
    });

    if (usr.error) {
        console.error(usr.error);
        toast(usr.error.message ?? "Unknown error");
    }
});
</script>

<template>
    <div class="min-h-screen flex items-center justify-center p-4">
        <Card class="mx-auto min-w-md">
            <CardHeader>
                <CardTitle class="text-xl">Register</CardTitle>
                <CardDescription
                    >Create a Stargate Network account</CardDescription
                >
            </CardHeader>
            <CardContent>
                <form @submit="onSubmit">
                    <div class="grid gap-4">
                        <FormField v-slot="{ componentField }" name="username">
                            <FormItem>
                                <div class="grid gap-2">
                                    <FormLabel for="username"
                                        >Username</FormLabel
                                    >
                                    <FormControl>
                                        <Input
                                            id="username"
                                            v-bind="componentField"
                                            type="text"
                                            placeholder="some user"
                                            required
                                        />
                                    </FormControl>
                                    <FormMessage />
                                </div>
                            </FormItem>
                        </FormField>
                        <FormField v-slot="{ componentField }" name="email">
                            <FormItem>
                                <div class="grid gap-2">
                                    <FormLabel for="email">Email</FormLabel>
                                    <FormControl>
                                        <Input
                                            id="email"
                                            v-bind="componentField"
                                            type="email"
                                            placeholder="m@example.com"
                                            required
                                        />
                                    </FormControl>
                                    <FormMessage />
                                </div>
                            </FormItem>
                        </FormField>
                        <FormField v-slot="{ componentField }" name="password">
                            <FormItem>
                                <div class="grid gap-2">
                                    <FormLabel for="password"
                                        >Password</FormLabel
                                    >
                                    <FormControl>
                                        <Input
                                            id="password"
                                            v-bind="componentField"
                                            type="password"
                                            required
                                        />
                                    </FormControl>
                                    <FormMessage />
                                </div>
                            </FormItem>
                        </FormField>
                        <Button type="submit" class="w-full">Login</Button>
                        <Button variant="outline" class="w-full">
                            Continue with Discord
                        </Button>
                    </div>
                </form>
                <div class="mt-4 text-center text-sm">
                    Already have an account?
                    <a href="/auth/login" class="underline">Login here!</a>
                </div>
            </CardContent>
        </Card>
    </div>
</template>

// apps/sgn-dash/src/components/auth/register.tsx
"use client";
import { authClient } from "@/lib/auth-client";
import { zodResolver } from "@hookform/resolvers/zod";
import React from "react";
import { Controller, useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "../ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/card";
import { Field, FieldError, FieldGroup, FieldLabel } from "../ui/field";
import { Input } from "../ui/input";
import { toast } from "sonner";
import { redirect } from "next/navigation";
import { Separator } from "../ui/separator";

const formSchema = z.object({
  name: z.string(),
  email: z.email(),
  password: z.string(),
});

export default function RegisterForm() {
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      email: "",
      password: "",
    },
  });

  async function onSubmit(data: z.infer<typeof formSchema>) {
    const auth = await authClient.signUp.email({
      name: data.name,
      email: data.email,
      password: data.password,
    });

    if (auth.error) {
      toast.error(auth.error.message);
    } else {
      await authClient.signIn.email({
        email: data.email,
        password: data.password,
      });
      redirect("/");
    }
  }

  async function discordAuth(event: React.MouseEvent<HTMLButtonElement>) {
    event.preventDefault();
    await authClient.signIn.social({ provider: "discord" });
  }

  return (
    <Card className="w-[400px]">
      <CardHeader>
        <CardTitle>Register</CardTitle>
      </CardHeader>
      <CardContent>
        <form id="register-form" onSubmit={form.handleSubmit(onSubmit)}>
          <FieldGroup>
            <Controller
              name="name"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid}>
                  <FieldLabel htmlFor="register-form-name">Username</FieldLabel>
                  <Input
                    {...field}
                    id="register-form-name"
                    aria-invalid={fieldState.invalid}
                    placeholder="you"
                    type="text"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
            <Controller
              name="email"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid}>
                  <FieldLabel htmlFor="register-form-email">Email</FieldLabel>
                  <Input
                    {...field}
                    id="register-form-email"
                    aria-invalid={fieldState.invalid}
                    placeholder="you@email.com"
                    type="email"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
            <Controller
              name="password"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid}>
                  <FieldLabel htmlFor="register-form-password">
                    Password
                  </FieldLabel>
                  <Input
                    {...field}
                    id="register-form-password"
                    aria-invalid={fieldState.invalid}
                    type="password"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
          </FieldGroup>
        </form>
      </CardContent>
      <CardFooter>
        <Field orientation="vertical">
          <Button className="w-full" type="submit" form="register-form">
            Register with email
          </Button>
          <div className="flex items-center gap-1 w-full">
            <Separator className="flex-1" />
            <span className="flex-0 text-foreground/50 italic">or</span>
            <Separator className="flex-1" />
          </div>
          <Button
            className="w-full"
            onClick={discordAuth}
            type="button"
            variant="secondary"
          >
            Continue with Discord
          </Button>
        </Field>
      </CardFooter>
    </Card>
  );
}
