// app/pages/admin/dashboard.vue
<script setup lang="ts">
definePageMeta({
  middleware: ["admin"],
  layout: "admin",
});

const {data: stargates} = await useFetch("/api/stargates")
const {data: users} = await useFetch("/api/users")
</script>

<template>
  <main class="flex flex-col gap-4 mt-4">
    <div class="flex gap-4 w-full">
      <Card class="flex-1">
        <CardHeader>
          <CardTitle>Active Stargates</CardTitle>
        </CardHeader>
        <CardContent>
          <h1
            class="scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance"
          >
            {{stargates?.length ?? 0}}
          </h1>
        </CardContent>
      </Card>
      <Card class="flex-1">
        <CardHeader>
          <CardTitle>Registered Users</CardTitle>
        </CardHeader>
        <CardContent>
          <h1
            class="scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance"
          >
            {{users?.length ?? "Data didnt load"}}
          </h1>
        </CardContent>
      </Card>
    </div>
    <Card>
      <CardHeader>
        <CardTitle>Users Overview</CardTitle>
      </CardHeader>
      <CardContent>
        {{users}}
      </CardContent>
      <CardFooter></CardFooter>
    </Card>    
  </main>
</template>

// src/app/admin/dashboard/page.tsx
import { DataTable } from "@/components/admin/tables/data-table";
import { columns as stargate_col } from "@/components/admin/tables/stargate/columns";
import { columns as user_col } from "@/components/admin/tables/users/columns";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useReactTable } from "@tanstack/react-table";
import { user } from "database/src/auth-schema";
import { db } from "database/src/db";
import { stargate } from "database/src/schema";

export default async function AdminDashboard() {
  const stargates = await db.select().from(stargate);
  const users = await db.select().from(user);

  return (
    <main className="space-y-4">
      <div className="flex gap-4">
        <Card className="flex-1">
          <CardHeader>
            <CardTitle>Active Stargates</CardTitle>
          </CardHeader>
          <CardContent>{stargates.length} Total Gates</CardContent>
        </Card>
        <Card className="flex-1">
          <CardHeader>
            <CardTitle>Registered Users</CardTitle>
          </CardHeader>
          <CardContent>{users.length} Total Users</CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Stargate Overview</CardTitle>
          <CardDescription>Shows the 5 most recently updated stargates</CardDescription>
          <CardContent className="mt-4">
            <DataTable columns={stargate_col} data={stargates.slice(0, 5)} />
          </CardContent>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>User Overview</CardTitle>
          <CardDescription>Shows the 5 most recently created users</CardDescription>
          <CardContent className="mt-4">
            <DataTable columns={user_col} data={users.slice(0, 5)} />
          </CardContent>
        </CardHeader>
      </Card>
    </main>
  );
}
