// app/pages/auth/login.vue
<script setup lang="ts">
definePageMeta({
  layout: "empty",
});

import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { toast } from "vue-sonner";

const auth = useAuthClient();

const formSchema = toTypedSchema(
  z.object({
    email: z.string().email("Invalid email address"),
    password: z.string(),
  }),
);

const form = useForm({
  validationSchema: formSchema,
});

const onSubmit = form.handleSubmit(async (values) => {
  const usr = await auth.signIn.email({
    email: values.email,
    password: values.password,
  });

  if (usr.data?.user) {
    navigateTo("/");
  } else {
    toast.error(usr.error?.message || "Unknown error");
  }
});

const discordLogin = async (e: FormDataEvent) => {
  e.preventDefault();
  const auth = useAuthClient();
  auth.signIn.social({
    provider: "discord",
  });
};
</script>

<template>
  <div class="min-h-screen flex items-center justify-center p-4">
    <Card class="mx-auto min-w-md">
      <CardHeader>
        <CardTitle class="text-xl">Login</CardTitle>
      </CardHeader>
      <CardContent>
        <form @submit="onSubmit">
          <div class="grid gap-4">
            <FormField v-slot="{ componentField }" name="email">
              <FormItem>
                <div class="grid gap-2">
                  <FormLabel for="email">Email</FormLabel>
                  <FormControl>
                    <Input
                      id="email"
                      v-bind="componentField"
                      type="email"
                      placeholder="m@example.com"
                      required
                    />
                  </FormControl>
                  <FormMessage />
                </div>
              </FormItem>
            </FormField>
            <FormField v-slot="{ componentField }" name="password">
              <FormItem>
                <div class="grid gap-2">
                  <FormLabel for="password">Password</FormLabel>
                  <FormControl>
                    <Input
                      id="password"
                      v-bind="componentField"
                      type="password"
                      required
                    />
                  </FormControl>
                  <FormMessage />
                </div>
              </FormItem>
            </FormField>
            <Button type="submit" class="w-full">Login</Button>
            <Button variant="outline" class="w-full" @click="discordLogin">
              Continue with Discord
            </Button>
          </div>
        </form>
        <div class="mt-4 text-center text-sm">
          Don't have an account?
          <a href="/auth/register" class="underline">Register here!</a>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

// src/components/auth/login.tsx
"use client";
import { authClient } from "@/lib/auth-client";
import { zodResolver } from "@hookform/resolvers/zod";
import React from "react";
import { Controller, useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "../ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "../ui/card";
import { Field, FieldError, FieldGroup, FieldLabel } from "../ui/field";
import { Input } from "../ui/input";

const formSchema = z.object({
  email: z.email(),
  password: z.string(),
});

export default function LoginForm() {
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  async function onSubmit(data: z.infer<typeof formSchema>) {
    await authClient.signIn.email({
      email: data.email,
      password: data.password,
    });
  }

  async function discordAuth(event: React.MouseEvent<HTMLButtonElement>) {
    event.preventDefault();
    await authClient.signIn.social({ provider: "discord" });
  }

  return (
    <Card className="w-[400px]">
      <CardHeader>
        <CardTitle>Login</CardTitle>
      </CardHeader>
      <CardContent>
        <form id="login-form" onSubmit={form.handleSubmit(onSubmit)}>
          <FieldGroup>
            <Controller
              name="email"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid}>
                  <FieldLabel htmlFor="login-form-email">
                    Email
                  </FieldLabel>
                  <Input
                    {...field}
                    id="login-form-email"
                    aria-invalid={fieldState.invalid}
                    placeholder="you@email.com"
                    type="email"
                  />
                  {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
                </Field>
              )}
            />
            <Controller
              name="password"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid}>
                  <FieldLabel htmlFor="login-form-password">
                    Password
                  </FieldLabel>
                  <Input
                    {...field}
                    id="login-form-password"
                    aria-invalid={fieldState.invalid}
                    type="password"
                  />
                  {fieldState.invalid && <FieldError errors={[fieldState.error]} />}
                </Field>
              )}
            />
          </FieldGroup>
        </form>
      </CardContent>
      <CardFooter>
        <Field orientation="vertical">
          <Button className="w-full" type="submit" form="login-form">Login with email</Button>
          <Button className="w-full" onClick={discordAuth} type="button" variant="secondary">Login with Discord</Button>
        </Field>
      </CardFooter>
    </Card>
  );
}
